version: '3.1'
services:
    postgres:
        image: postgres:14.0
        container_name: 'postgresdb'
        restart: always
        ports:  
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: file
